### ISSUE TITLE
Support for oauth2 endpoint

### ISSUE THREAD

**Issue by rhysawilliams2010** [sypht-team/sypht-node-client#1]
Please can you update the client to support the new oauth2 authentication system?
https://docs.sypht.com/#tag/Authenticate/paths/~1oauth2~1token/post

**Comment by jonsypht** [comment]
@rhysawilliams2010 Thanks for raising this. Yes, we are currently in-progress on updating our client sdks to support oauth2 endpoint. We'll keep you posted! 👍

**Comment by jonsypht** [comment]
@rhysawilliams2010 you can now update your package to 0.11.1 for oauth2 support

Cheers!
